language: minimal
os: linux
dist: bionic
sudo: enabled
addons:
  snaps:
    - name: snapcraft
      confinement: classic
      # candidate is needed for https://github.com/snapcore/snapcraft/pull/3218,
      # which will go into 4.1.2, remove when 4.1.2 hits stable
      channel: candidate
    - name: lxd
env:
  global:
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8
      # build with lxd because travis doesn't support focal yet, so we can't build
      # natively
    - SNAPCRAFT_BUILD_ENVIRONMENT=lxd

install:
  - sudo apt-get remove lxd-client lxc -y
  - sudo apt-get autoremove
  - sudo /snap/bin/lxd init --auto
  - sudo usermod --append --groups lxd $USER

script:
  - sg lxd 'snapcraft'
  - sudo unsquashfs -d prime core20*.snap
  - make test
